dist: trusty
addons:
  sonarcloud:
    organization: "shouwy-github" # the key of the org you chose at step #3
    token:
      secure: 22b5dc83047a64bda8349a8701b460cdbd015cc9 # encrypted value of your token


script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - sonar-scanner -Dsonar.projectKey=shouwy_SeriesFront -Dsonar.organization=shouwy-github -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=22b5dc83047a64bda8349a8701b460cdbd015cc9